<?php
$this->image = 'http://placehold.it/250x140/';
$this->url = 'https://www.forewordreviews.com/reviews/lord-of-misrule/';
$this->type = 'Book Review';
$this->type_slug = 'book-review';
$this->author = $this->artist;
$this->snippet = 'If you love to read great books, here are 10 reasons why you\'ll love reading indie books.';
$this->tags = array(
	'#philosophy',
	'#selfhelp',
	'#bookreviews',
	'#life',
	'#ideas',
	'#future',
);
?>
<div class="snippet-wrapper">
<article class="snippet <?= $this->escapeHtmlAttr($this->type_slug); ?>">
	<aside>
		<a href="<?= $this->escapeHtmlAttr($this->url); ?>"><img src="<?= $this->escapeHtmlAttr($this->image); ?>"></a>
		<?= $this->partial('/album/album/social-share.phtml', array(
			'url' => $this->url,
			'title' => $this->title,
			'snippet' => $this->snippet,
			'image' => $this->image,
			)); ?>
	</aside>
	<main>
		<header>
			<?= $this->partial('/album/album/tags.phtml', array('tags' => $this->tags)); ?>
			<p class="post-type"><?= $this->escapeHtml($this->type); ?></p>
			<h1><a href="<?= $this->escapeHtmlAttr($this->url); ?>"><?= $this->escapeHtml($this->title); ?></a></h1>
			<p>by <?= $this->escapeHtml($this->author); ?></p>
		</header>
		<p><?= $this->escapeHtml($this->snippet); ?> <a href="<?= $this->escapeHtmlAttr($this->url); ?>">Read More</a></p>
	</main>
</article>
</div>
