<div class="social-share">
	<a href="https://www.facebook.com/sharer/sharer.php?u=<?= $this->escapeUrl($this->url) ?>" target="_blank">
		<img src="http://placehold.it/30x30/8800ff">
	</a>
	<a href="https://twitter.com/share?url=<?= $this->escapeUrl($this->url) ?>" target="_blank">
		<img src="http://placehold.it/30x30/880088">
	</a>
	<a href="https://plus.google.com/share?url=<?= $this->escapeUrl($this->url) ?>" target="_blank">
		<img src="http://placehold.it/30x30/008888">
	</a>
	<a href="http://pinterest.com/pin/create/button/?url=<?= $this->escapeUrl($this->url) ?>&amp;description=<?= $this->escapeUrl($this->title.': '.$this->snippet) ?>&amp;media=<?= $this->escapeUrl($this->image) ?>" target="_blank">
		<img src="http://placehold.it/30x30/00ff88">
	</a>
	<a href="http://www.linkedin.com/shareArticle?mini=true&amp;url=<?= $this->escapeUrl($this->url) ?>&amp;title=<?= $this->escapeUrl($this->title) ?>&amp;summary=<?= $this->escapeUrl($this->snippet) ?>&source=Foreword+Reviews" target="_blank">
		<img src="http://placehold.it/30x30/0088ff">
	</a>
</div>