<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('Foreword Reviews')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink()
				->prependStylesheet($this->basePath() . '/css/style.css') ?>

		<!-- Scripts -->
		<?php echo $this->headScript() ?>

	</head>
	<body>
		<div class="primary-header-wrapper">
			<header class="primary-header">
				<nav class="primary-nav-account">
					<p>
						<a href="/login/">Log In</a> or <a href="/register/">Sign Up</a>!
						<a href="/search/"><img src="http://placehold.it/16x16/"></a>
					</p>
				</nav>
				<a href="/" class="primary-logo"><img src="http://placehold.it/45x60/"></a>
				<a href="/" class="primary-logo-name"><img src="http://placehold.it/159x41/"></a>
				<nav class="primary-nav">
					<ul>
						<li><a href="/reviews/">Book Reviews</a></li>
						<li><a href="/articles/">Articles</a></li>
						<li><a href="/blog/">Blog</a></li>
						<li><a href="/subscribe/">Subscribe</a></li>
						<li><a href="/promotions/">Promotions</a></li>
						<li><a href="https://indiefab.forewordreviews.com/">Awards</a></li>
						<li><a href="/services/">For Publishers</a></li>
					</ul>
				</nav>
			</header>
		</div>
		<main class="primary-main">
			<?= $this->content ?>
		</main>
		<div class="primary-footer-wrapper">
			<footer class="primary-footer">
				<p class="primary-footer-nav">
					<a href="/about/">About Us</a>
					<a href="/faq/">FAQs</a>
					<a href="/contact/">Contact Us</a>
					<a href="/privacy/">Privacy Policy</a>
					<a href="/terms/">Terms</a>
				</p>
				<p>&copy; <?= date("Y") ?> Foreword Magazine, Inc. All rights reserved.</p>
				<h1 class="primary-social-follow-header">Choose Your Conversation:</h1>
				<p class="primary-social-follow">
					<a href="https://www.twitter.com/ForewordReviews" target="_blank">
						<img src="http://placehold.it/19x19/8800ff">
					</a>
					<a href="https://www.facebook.com/forewordreviews" target="_blank">
						<img src="http://placehold.it/19x19/ff0088">
					</a>
					<a href="https://plus.google.com/+forewordreviews" target="_blank">
						<img src="http://placehold.it/19x19/00ff88">
					</a>
					<a href="https://www.linkedin.com/forewordreviews" target="_blank">
						<img src="http://placehold.it/19x19/0088ff">
					</a>
					<a href="https://www.pinterest.com/forewordreviews" target="_blank">
						<img src="http://placehold.it/19x19/ff8800">
					</a>
					<a href="https://www.facebook.com/forewordreviews" target="_blank">
						<img src="http://placehold.it/19x19/88ff00">
					</a>
				</p>
			</footer>
		</div>
		<?php echo $this->inlineScript() ?>
	</body>
</html>
